<?php

/* How to make new entries here for non-packaged languages:

-- 'code' should match the name of the directory for the language under \lang
.-- 'name' is the name that will be displayed in the language selection list (in Users and Display Setup)
-- 'rtl' only needs to be set for right-to-left languages like Arabic and Hebrew
-- 'encoding' used in translation file
-- 'version' always set to '' for manually installed languages.
-- 'path' installation path related to FA root (e.g. 'lang/en_US').
*/


$installed_languages = array (
  0 => 
  array (
    'code' => 'C',
    'name' => 'English',
    'encoding' => 'iso-8859-1',
  ),
  1 => 
  array (
    'name' => 'Arabic',
    'package' => 'ar_EG',
    'code' => 'ar_EG',
    'encoding' => 'utf-8',
    'version' => '2.3.0-2',
    'path' => 'lang/ar_EG',
    'rtl' => true,
  ),
  2 => 
  array (
    'name' => 'Bulgarian',
    'package' => 'bg_BG',
    'code' => 'bg_BG',
    'encoding' => 'utf-8',
    'version' => '2.3.0-1',
    'path' => 'lang/bg_BG',
  ),
  3 => 
  array (
    'name' => 'Danish',
    'package' => 'da_DK',
    'code' => 'da_DK',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/da_DK',
  ),
  4 => 
  array (
    'name' => 'Swiss German',
    'package' => 'de_CH',
    'code' => 'de_CH',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/de_CH',
  ),
  5 => 
  array (
    'name' => 'German',
    'package' => 'de_DE',
    'code' => 'de_DE',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/de_DE',
  ),
  6 => 
  array (
    'name' => 'Greek',
    'package' => 'el_GR',
    'code' => 'el_GR',
    'encoding' => 'UTF-8',
    'version' => '2.3.0-2',
    'path' => 'lang/el_GR',
  ),
  7 => 
  array (
    'name' => 'Australian English',
    'package' => 'en_AU',
    'code' => 'en_AU',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/en_AU',
  ),
  8 => 
  array (
    'name' => 'English (US)',
    'package' => 'en_US',
    'code' => 'en_US',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/en_US',
  ),
  9 => 
  array (
    'name' => 'Spanish (Argentina)',
    'package' => 'es_AR',
    'code' => 'es_AR',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/es_AR',
  ),
  10 => 
  array (
    'name' => 'Spanish (Chile)',
    'package' => 'es_CL',
    'code' => 'es_CL',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/es_CL',
  ),
  11 => 
  array (
    'name' => 'Spanish (Colombia)',
    'package' => 'es_CO',
    'code' => 'es_CO',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/es_CO',
  ),
  12 => 
  array (
    'name' => 'Spanish (Mexico)',
    'package' => 'es_MX',
    'code' => 'es_MX',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/es_MX',
  ),
  13 => 
  array (
    'name' => 'Spanish (Panama)',
    'package' => 'es_PA',
    'code' => 'es_PA',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/es_PA',
  ),
  14 => 
  array (
    'name' => 'French',
    'package' => 'fr_FR',
    'code' => 'fr_FR',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/fr_FR',
  ),
  15 => 
  array (
    'name' => 'Hungarian',
    'package' => 'hu_HU',
    'code' => 'hu_HU',
    'encoding' => 'iso-8859-2',
    'version' => '2.3.0-1',
    'path' => 'lang/hu_HU',
  ),
  16 => 
  array (
    'name' => 'Indonesian',
    'package' => 'id_ID',
    'code' => 'id_ID',
    'encoding' => 'utf-8',
    'version' => '2.3.0-2',
    'path' => 'lang/id_ID',
  ),
  17 => 
  array (
    'name' => 'Dutch (Belgium)',
    'package' => 'nl_BE',
    'code' => 'nl_BE',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/nl_BE',
  ),
  18 => 
  array (
    'name' => 'Dutch (Netherlands)',
    'package' => 'nl_NL',
    'code' => 'nl_NL',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/nl_NL',
  ),
  19 => 
  array (
    'name' => 'Polish',
    'package' => 'pl_PL',
    'code' => 'pl_PL',
    'encoding' => 'iso-8859-2',
    'version' => '2.3.0-15',
    'path' => 'lang/pl_PL',
  ),
  20 => 
  array (
    'name' => 'Portuguese (Brazil)',
    'package' => 'pt_BR',
    'code' => 'pt_BR',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/pt_BR',
  ),
  21 => 
  array (
    'name' => 'Portuguese',
    'package' => 'pt_PT',
    'code' => 'pt_PT',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/pt_PT',
  ),
  22 => 
  array (
    'name' => 'Russian',
    'package' => 'ru_RU',
    'code' => 'ru_RU',
    'encoding' => 'iso-8859-5',
    'version' => '2.3.0-1',
    'path' => 'lang/ru_RU',
  ),
  23 => 
  array (
    'name' => 'Bosnian',
    'package' => 'sh_BA',
    'code' => 'sh_BA',
    'encoding' => 'iso-8859-2',
    'version' => '2.3.0-1',
    'path' => 'lang/sh_BA',
  ),
  24 => 
  array (
    'name' => 'Swedish',
    'package' => 'sv_SE',
    'code' => 'sv_SE',
    'encoding' => 'iso-8859-1',
    'version' => '2.3.0-1',
    'path' => 'lang/sv_SE',
  ),
  25 => 
  array (
    'name' => 'Chinese (Simplified)',
    'package' => 'zh_CN',
    'code' => 'zh_CN',
    'encoding' => 'utf-8',
    'version' => '2.3.0-1',
    'path' => 'lang/zh_CN',
  ),
  26 => 
  array (
    'name' => 'Chinese (Traditional)',
    'package' => 'zh_TW',
    'code' => 'zh_TW',
    'encoding' => 'utf-8',
    'version' => '2.3.0-1',
    'path' => 'lang/zh_TW',
  ),
);

$dflt_lang = 'de_DE';
?>
